# Generated by Django 3.2.18 on 2023-03-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_desc',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
