# Generated by Django 3.2.18 on 2023-03-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20230316_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
