# Generated by Django 3.2.18 on 2023-03-15 20:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_category_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='uid',
            new_name='cat_uid',
        ),
        migrations.CreateModel(
            name='ads',
            fields=[
                ('ads_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ads_title', models.CharField(max_length=30)),
                ('ads_decsription', models.TextField(blank=True, max_length=100)),
                ('category_id', models.ForeignKey(blank=True, db_column='cat_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.category')),
            ],
        ),
    ]
