# Generated by Django 3.2.18 on 2023-03-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20230317_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_desc',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=30),
        ),
    ]
