# Generated by Django 3.2.18 on 2023-03-16 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0010_alter_category_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='user_id',
            field=models.ForeignKey(db_column='uid', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
