# Generated by Django 3.2.18 on 2023-03-16 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_ads_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='user_id',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='ads',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='listed_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
