# Generated by Django 3.2.18 on 2023-03-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20230317_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ads',
            name='tags',
            field=models.ManyToManyField(to='listings.tags'),
        ),
    ]
