# Generated by Django 3.2.18 on 2023-03-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_ads_ads_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ads_images',
            field=models.ImageField(default='', upload_to='ads_list/'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(default='Blank', max_length=150),
        ),
    ]
