# Generated by Django 3.2.18 on 2023-03-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20230319_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='tags',
        ),
    ]
