# Generated by Django 3.2.18 on 2023-03-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_remove_ads_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ads_images',
            field=models.ImageField(default='', upload_to='media/ads_list/'),
        ),
    ]
