# Generated by Django 3.2.18 on 2023-03-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_alter_ads_ads_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ads_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_photos', models.FileField(upload_to='ads_list/')),
            ],
        ),
    ]
