# Generated by Django 3.2.18 on 2023-03-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_ads_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='ads_images',
        ),
        migrations.AddField(
            model_name='ads_images',
            name='ads_name',
            field=models.ForeignKey(db_column='ads_title', null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.ads'),
        ),
        migrations.AlterField(
            model_name='ads_images',
            name='ads_photos',
            field=models.FileField(upload_to='ads_list/{ads_id}/'),
        ),
    ]
