# Generated by Django 3.2.18 on 2023-03-24 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0020_auto_20230324_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_images',
            name='userID',
            field=models.ForeignKey(db_column='uid', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ads_images',
            name='ads_photos',
            field=models.FileField(upload_to='ads_list/'),
        ),
    ]
