# Generated by Django 3.2.18 on 2023-03-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_auto_20230324_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads_images',
            old_name='userID',
            new_name='user_ID',
        ),
    ]
