# Generated by Django 3.2.18 on 2023-03-24 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0023_rename_userid_ads_images_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='category_id',
            field=models.ForeignKey(blank=True, db_column='Category.cat_uid', null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.category'),
        ),
        migrations.AlterField(
            model_name='ads_images',
            name='ads_id',
            field=models.ForeignKey(db_column='ads.ads_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.ads'),
        ),
        migrations.AlterField(
            model_name='ads_images',
            name='user_ID',
            field=models.ForeignKey(db_column='User.uid', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
