# Generated by Django 3.2.18 on 2023-03-25 20:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_auto_20230325_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryView',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.category')),
            ],
            bases=('listings.category',),
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='ads_decsription',
            new_name='ads_description',
        ),
        migrations.AlterField(
            model_name='ads',
            name='category_id',
            field=models.ForeignKey(blank=True, db_column='cat_uid', null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.category'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='listed_date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
