# Generated by Django 3.2.18 on 2023-03-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_auto_20230326_0212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryView',
        ),
    ]
