# Generated by Django 3.2.18 on 2023-03-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_delete_categoryview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ListingCategory',
        ),
    ]
