# Generated by Django 3.2.18 on 2023-03-25 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_rename_category_listingcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='listed_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
