# Generated by Django 3.2.18 on 2023-03-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_alter_ads_listed_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingCategory',
            new_name='Listing_Category',
        ),
    ]
