# Generated by Django 3.2.18 on 2023-03-26 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_alter_ads_images_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads_images',
            name='ads_id',
            field=models.ForeignKey(db_column='ads_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.ads'),
        ),
    ]
