# Generated by Django 3.2.18 on 2023-03-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_alter_ads_images_ads_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads_images',
            name='ads_photos',
            field=models.ImageField(upload_to='ads_list/'),
        ),
    ]
