# Generated by Django 3.2.18 on 2023-03-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_alter_ads_images_ads_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads_images',
            name='ads_photos',
            field=models.FileField(upload_to='ads_list/'),
        ),
    ]
