# Generated by Django 3.2.18 on 2023-04-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_alter_ads_images_ads_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads_images',
            name='ads_photos',
            field=models.ImageField(upload_to='ads_list/'),
        ),
    ]
