# Generated by Django 3.2.18 on 2023-04-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_alter_ads_images_ads_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
