# Generated by Django 3.2.18 on 2023-04-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_ads_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads_images',
            name='user_ID',
        ),
    ]
