# Generated by Django 3.2.18 on 2023-04-21 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_remove_ads_images_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
