# Generated by Django 3.2.18 on 2023-04-30 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0038_alter_ads_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='no_of_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ads_images',
            name='ads_photos',
            field=models.ImageField(upload_to='ads_list'),
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_id', models.ForeignKey(db_column='ads_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.ads')),
                ('user_id', models.ForeignKey(db_column='uid', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
