# Generated by Django 3.2.18 on 2023-03-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_location_address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
